### ISSUE TITLE
Confidenciality and cyber-security

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/HackLab#5]
It is usually a good practice not to include usernames+passwords hardcoded in source code, as this leads to security holes and vulnerabilities (in this case, at the level of the ASROB organization).

I'm refering to [this file](https://github.com/asrob-uc3m/HackLab/blob/3cb634d2ead786f3fbbf3841dbc3bf5d6966fa70/IoTeces/IoTez_2_firmware/IoTez_2_firmware.ino):
```cpp
const char* ssid = "ASROB";
const char* password = "asrobchallenge";
``` 

Please change this as soon as possible and try to avoid adding this information to source codes in future codes. :wink:

**Comment by jgvictores** [comment]
Reopening:
- Use https://rtyley.github.io/bfg-repo-cleaner/ to clean history.
- Same with duplicate: https://github.com/Rodriwp/IoTeces

**Comment by David-Estevez** [comment]
IMHO I think this is no longer an issue since the credentials of the router have changed. What do you think?

**Comment by jgvictores** [comment]
Ok.
